env:
  browser: true
  es6: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  "react/jsx-first-prop-new-line": [1, multiline]
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
